name: DevSecOps CI/CD TODO

on:
  push:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/todo:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gitleaks Scan
        uses: zricethezav/gitleaks-action@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Maven
        run: mvn clean package

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t $DOCKER_IMAGE_NAME .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.DOCKER_IMAGE_NAME }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push Docker Image
        run: docker push $DOCKER_IMAGE_NAME
